sonar.projectKey=planner-uc-frontend
sonar.projectName=Planner UC - Frontend
sonar.projectVersion=0.1.0

sonar.sources=app,components,hooks,lib,store,types
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**,**/*.config.*,**/components/ui/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
