sonar.projectKey=planner-uc-solver
sonar.projectName=Planner UC - Solver
sonar.projectVersion=0.1.0

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/htmlcov/**
sonar.test.exclusions=tests/test_integration.py
sonar.sourceEncoding=UTF-8
